[alias]
xtask = "run --package xtask --bin xtask --"

[target.'cfg(target_os = "none")']
runner = "gdb-multiarch -q"

rustflags = [
  "-C", "link-arg=-Tlink.ld",
  "-C", "linker=lld",
]

[build]
target = "mipsel-unknown-none"

[unstable]
build-std = ["core"]
